# Generated by Django 4.0.6 on 2022-07-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMUeat', '0002_alter_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='password',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
